name: Node
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 24
          - 26
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          node --version
          npm --version
          npm install
          npm test
        env:
          CI: true
      - name: Upload code coverage
        if: matrix.node-version == 24
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage/clover.xml
